### ISSUE TITLE
Remove Microsoft Teams support

### ISSUE THREAD

**Issue by danielmilner** [firetreedesign/hey-notify#78]
I no longer have access to a Microsoft Teams account that has access to channels. Also, Microsoft is retiring Office 365 connectors in favor of Workflows. This feature may come back in the future, but for now, it is being removed.

https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/

### Tasks

- [x] Remove the Microsoft Teams service
- [x] Remove Microsoft Teams from the promotional graphics
- [x] Remove Microsoft Teams documentation pages
